services:
  - type: web
    name: portfolio
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # This indicates you'll manually add this in the Render dashboard
    healthCheckPath: /
    autoDeploy: true
